### ISSUE TITLE
Issues building with Boost

### ISSUE THREAD

**Issue by acil-bwh** [acil-bwh/ChestImagingPlatform#2]
VTK_USE_BOOST has been removed in VTK6 and has been replaced by:
- Module_vtkInfovisBoostGraphAlg

**Comment by rjosest** [comment]
VTK build system has switched to a modular structure. More details can are here:
http://www.vtk.org/Wiki/VTK/Build_System_Migration

VTK_USE_BOOST is not declared any more as a cache variable. Instead, we can detect if the module that we are targeting (vtkInfovisBoostGraphAlgorithms) is part of VTK and then defined a CIP_USE_BOOST variable
In the future we could cache this variable to be able to control at config time if CIP will use BOOST or not.
