### ISSUE TITLE
Test do not compile in Windows

### ISSUE THREAD

**Issue by acil-bwh** [acil-bwh/ChestImagingPlatform#3]
There is a problem with Windows and dllimport dllexport with all the CLI Test. Jinho is looking at this.

**Comment by jonieva** [comment]
This problem was solved by Jinho in the tests that we currently had in place. In case that new tests fail, check https://github.com/acil-bwh/ChestImagingPlatform/commit/7eebd1b8c8b75eefc2b521323229b46545395ea2 for some examples
