### ISSUE TITLE
build issues on macos/ubuntu: cannot connect to github.com

### ISSUE THREAD

**Issue by kiwixiao** [acil-bwh/ChestImagingPlatform#43]
Hi developers

I was trying to build the file, however, it showed up an error message says: "cannot connect to github.com"
I figured out by looking into the build folder, for example, there is a file called: */CIPPython-prefix/tmp/CIPPython.gitclone.cmake, then open this file and find the line says: clone --no--checkout * "git://github.com/*" and replace the "git://" to "https://"
(no quotation needed in the actual code)

As I am new to git and make, so I am not sure is this the git setup issue or some make files need to be update or neither.

Looking forward to hearing any comments and suggestion.
Thanks

**Comment by rjosest** [comment]
Hello,

That file is automatically generated by the CMake building script. It is recommended that you build your code in a different location that your source code. Are you doing that?

If you are having issues building CIP, a good alternative is using our docker image: https://hub.docker.com/r/acilbwh/chestimagingplatform

HTH

**Comment by kiwixiao** [comment]
I ended up with using docker image after I experienced python library inconsistency conflicts. The docker just so easy to use. Thanks for the link. > Hello,
> 
> 
> 
> That file is automatically generated by the CMake building script. It is recommended that you build your code in a different location that your source code. Are you doing that?
> 
> 
> 
> If you are having issues building CIP, a good alternative is using our docker image: https://hub.docker.com/r/acilbwh/chestimagingplatform
> 
> 
> 
> HTH
> 
>
