### ISSUE TITLE
Help: docker image running cip_compute_vessel_particles.py with error: 'CIP_PATH' not set.

### ISSUE THREAD

**Issue by kiwixiao** [acil-bwh/ChestImagingPlatform#44]

**Comment by kiwixiao** [comment]
This has been fixed and I have more build logs in my gist if anyone is interested to see. Thanks.
https://gist.github.com/kiwixiao/f7dee7a7c33eb57990ba8dc48ba54b57

**Comment by rjosest** [comment]
Hi Kiwixiao,

Thanks for sharing these notes. Your feedback is helpful to improve the building instructions.

We have been improving our compatibility with C++1 in the develop branch.

Thanks

Raul

**Comment by kiwixiao** [comment]
@rjosest You are welcome. I also packed a ubuntu docker image with pre-build CIP, which is for my M1 mac to use. I hope it is ok for me to push this to my Docker hub, I have put clarification that I am just packing your source code. And the purpose of that image is just to allow some M1 mac users to run it on their machine without worrying to set it up. Here is the link to the image, and let me know if you want me to delete it. (https://hub.docker.com/repository/docker/zedshao/ubuntu_emulate_x86_packed_cip)
FYI: I can only build it without turning on boost, there are some errors with the boost library which I have not figured out. Let me know if in the future there are some updates/instructions regards building with boost on.

KiwiXiao
