### ISSUE TITLE
GeneratePartialLungLabelMap exception

### ISSUE THREAD

**Issue by rjosest** [acil-bwh/ChestImagingPlatform#5]
I run into an interesting exception that might highlight some underlying problem with GeneratePartialLungLabelMap exception.

The experiment is as follows. When I execute:
GeneratePartialLungLabelMap -c 026658003996_INSP_STD_L3_ECLIPSE.nhdr -o tmp.nrrd --lsr 4

Things run as expected

However, if you execute:
GeneratePartialLungLabelMap -c 026658003996_INSP_STD_L3_ECLIPSE.nhdr -o tmp.nrrd --lsr 4 --lcv -1100 --lrv 1024 --ucv 1024 --urv 1024

I get the following error:
```Reading CT from file...
Clipping low CT image values...
Clipping upper CT image values...
Executing partial lung filter...
Exception caught segmenting lungs:
itk::ExceptionObject (0x7f8155b00a98)
Location: "unknown" 
File: /Users/rjosest/src/devel/ChestImagingPlatformPrivate-build/ITKv4/Modules/Core/Common/include/itkExtractImageFilter.hxx
Line: 99
Description: itk::ERROR: ExtractImageFilter(0x7f8155b00080): Extraction Region not consistent with output image
Writing lung mask image...
Exception caught while writing lung mask:
itk::ExceptionObject (0x7f8156a00a98)
Location: "unknown" 
File: /Users/rjosest/src/devel/ChestImagingPlatformPrivate-build/ITKv4/Modules/Core/Common/include/itkExtractImageFilter.hxx
Line: 99
Description: itk::ERROR: ExtractImageFilter(0x7f8156a00080): Extraction Region not consistent with output image
DONE. ```

**Comment by jcross186** [comment]
I was able to reproduce this behavior. However, if you set --lrv to -1024, everything works as expected. Will close this issue.
