### ISSUE TITLE
Issues with Region/Type hierarchy

### ISSUE THREAD

**Issue by rjosest** [acil-bwh/ChestImagingPlatform#6]
Just run into a Region/Type hierarchy issue. The issue can be reproduced as follows

GenerateSimpleLungMask -i <CIP_SOURCE_DIR>/Testing/Data/Input/ct-64.nrrd -o /tmp/kk.nrrd
ExtractChestLabelMap -r WholeLung -i /tmp/kk.nrrd -o /tmp/kk2.nrrd

I think the issue is related to the fact that Whole Lung has two potential hierarchical groups:
Left L + Right L
Upper Third + Middle Third + Lower Third

SimpleLungMask produces the second grouping that it does not seem to be properly addressed by itkCIPExtractChestLabelMapImageFilter

NOTE: This has to be tested in the release branch. GenerateSimpleLungMask is using the new convention in the Release Branch.

**Comment by acil-bwh** [comment]
Latest commit to development branch fixes this issue. CheckSubordinateSuperiorChestRegionRelationship in cipChestConventions has been corrected.
